### ISSUE TITLE
ECharts render error when directly setComponents to the editor

### ISSUE THREAD

**Issue by xinnai** [jvas28/grapesjs-echarts#7]
Hi, thank you very much for this amazing work ! Please help me with my problem, thank you!!!!
In my case,  I use the data `gjs-html` and `gjs-css` from localStorage to send to server. Then I use the code bellow to init the editor, But all the grapesjs-echart dom cannot display on the editor.
`
this.editor.setComponents(gjs-html string)
this.editor.setStyle(gjs-css string)
`
Some gjs-html may like this
`<div id="ikir" data-ecg-series="[{&quot;id&quot;:1612336424717,&quot;label&quot;:&quot;Category 1&quot;,&quot;value&quot;:100,&quot;color&quot;:null},{&quot;id&quot;:1612336424894,&quot;label&quot;:&quot;Category 2&quot;,&quot;value&quot;:100,&quot;color&quot;:null}]" data-ecg-theme="" data-ecg-options="{&quot;series&quot;:[{&quot;type&quot;:&quot;bar&quot;,&quot;data&quot;:[{&quot;value&quot;:100,&quot;name&quot;:&quot;Category 1&quot;,&quot;itemStyle&quot;:{&quot;color&quot;:null}},{&quot;value&quot;:100,&quot;name&quot;:&quot;Category 2&quot;,&quot;itemStyle&quot;:{&quot;color&quot;:null}}]}],&quot;xAxis&quot;:[{&quot;data&quot;:[&quot;Category 1&quot;,&quot;Category 2&quot;]}],&quot;yAxis&quot;:[{&quot;type&quot;:&quot;value&quot;}]}"></div><script>var items = document.querySelectorAll('#ikir');
          for (var i = 0, len = items.length; i < len; i++) {
            (function(){var t=this;window.$grapesEcharts||(window.$grapesEcharts={themes:[]});var e=JSON.parse(this.getAttribute("data-ecg-options")),n=this.getAttribute("data-ecg-theme")||null,i=function(){try{var i=echarts.getInstanceByDom(t);i&&echarts.dispose(i);var r=echarts.init(t,n);e&&r.setOption(e)}catch(t){console.log(t)}},r=function(){if(n)if(window.$grapesEcharts.themes.includes(n))i();else{var t=document.createElement("script");t.onload=i,window.$grapesEcharts.themes.push(n),t.src="https://unpkg.com/echarts@4.6.0/theme/".concat(n,".js"),document.body.appendChild(t)}else i()};if("undefined"==typeof echarts){var o=document.createElement("script");o.onload=r,o.src="https://cdnjs.cloudflare.com/ajax/libs/echarts/4.6.0/echarts-en.min.js",document.body.appendChild(o)}else r()}.bind(items[i]))();
          }</script>
`

and gjs-css like this:

`

* { box-sizing: border-box; } body {margin: 0;}*{box-sizing:border-box;}body{margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;}#ikir{width:300px;min-height:100px;}

`

**Comment by jvas28** [comment]
Hello @xinnai, sorry for the delay. I would suggest to also store`gjs-components` and `gjs-styles` and use both of them when loading your site, `gjs-html` and `gjs-css` are for the published version of your site.  

Ref to:
https://grapesjs.com/docs/modules/Storage.html#store-and-load-templates

**Comment by xinnai** [comment]
@jvas28 Thanks a lot for your quick replay, you are right I should pass `gjs-components` and `gjs-styles`, and now my initialization of the editor is ok. But now I also have a problem with the `gjs-html ` when reload the page. 
The step is :
1. init the editor
`this.editor = grapesjs.init({
        container: "#gjs",
        fromElement: false,
        storageManager: {
          id: "gjs-", // Prefix identifier that will be used inside storing and loading
          type: "local", // Type of the storage
          autosave: true, // Store data automatically
          autoload: true, // Autoload stored data on init
        },
       
        plugins: [
          "gjs-preset-webpage",
          echartsPlugin
        ],
        
        pluginsOpts: {},
        
      });`

2. drag a bar-chart into editor,  set some data and theme in the traits, now look at gjs-html, it's right, both divs and scripts is there.
3. reload the page in Chrome, also set some data or theme in the traits, now look at  `gjs-html` , the scripts is gone...

This problem cause error when I publish my site, the chart cannot  be seen, I think this is because the scripts is missing, can you help? Thanks a lot!!!

**Comment by jvas28** [comment]
Hey @xinnai,

About problem one, I will consider adding default chart values, so when you drag the chart in you have something more than a white space, it's not actually related with the theme selection. 

About othersI think I will need a little more information. How are you storing all of this?

**Comment by xinnai** [comment]
I use the default local storage, the full code is here :
`initGrapesJs() {
      this.editor = grapesjs.init({
        container: "#gjs",
        fromElement: false,
        storageManager: {
          id: "gjs-", // Prefix identifier that will be used inside storing and loading
          type: "local", // Type of the storage
          autosave: true, // Store data automatically
          autoload: true, // Autoload stored data on init
          
        },
        plugins: [
          "gjs-preset-webpage",
          echartsPlugin
        ],
        
        pluginsOpts: {},
        
      });
    },`

Problem1:  I drag a chart and set  "Macarons" theme and datas, then I reload the page. After reload the chart got white again because the theme is missing.  If I  set "Macarons" theme again is also white, I must set a DIFFERENT theme then it will be ok
Problem2: After reload the <script> is missing too in `gjs-html`, you can test this by export code and open the index.html. The chart cannot be seen because of the missing script.

**Comment by jvas28** [comment]
Hi @xinnai, I marked this as a bug and will take care in the coming days.

**Comment by jvas28** [comment]
@xinnai I published a new version where your problem is fixed, please make sure to update the package.

**Comment by xinnai** [comment]
@jvas28 Thank you very much for your work! I tested this on version 0.0.20 and found the problems are still there.
Problem1:  Still has this problem.
Problem12: After RELOAD the <script> is not missing, but it's missing when I choose a new theme.

Am I use the correct version?
